### ISSUE TITLE
determine if there is ambiguity around 'Data:' requirement in Spec section 1

### ISSUE THREAD

**Issue by rossputin** [open-ecosystem-federation/federated-events-attributes-reasoning-alpha#1]
Hi Ben, this is just a nudge for me to talk to you about this bit of the spec.

I am not sure I understand the purpose of this section - probably me...

'Data: the logical/physical manifestation of the information (raw and refined) being made available for access as part of the...'

I am not sure if we are talking about the raw data here or the expertise on the participants side.

The event pipeline(s) feeding the ecosystem are one thing, ontologies around the expertise a participant can bring to bear are another.

**Comment by benghelps** [comment]
Ross, I think this is a naming convention problem. I think that what you call an "event pipeline" I call "data" or "database". We both agree that these data/events can be "raw" (i.e. largely outside of the ecosystem, with the exception of the publication of entity structures and identifiers) and "refined" (i.e. inferences, attestations, actions, etc. that are the tokens which form the core of the ecosystem)

**Comment by rossputin** [comment]
Ben - thanks, and also for your time via phone today, I think we discussed this one and I was happy with how it worked out.  I note that we will need to account for the both the event pipeline for the more complex event firehose scenarios we see in more 'industrial' ecosystems and the database for smaller scale simpler ecosystems like our first one or two illustrative examples.

I will move this ticket across to done accordingly.
