### ISSUE TITLE
reword to simplify spec section

### ISSUE THREAD

**Issue by rossputin** [open-ecosystem-federation/federated-events-attributes-reasoning-alpha#2]
'Every participant must map their proprietary data schema to the ontology and – where they reference data objects in their directory information that are not already described in the ontology – participants must publish definitions of these incremental terms as part of the ontology.'

Not being very helpful... I don't have a suggestion at this time but it is a little difficult (subjectively) to unpack this.

**Comment by benghelps** [comment]
Text updated
