### ISSUE TITLE
Review and provide feedback on the Draft RoE as presented in the workshop 3/4/2020

### ISSUE THREAD

**Issue by rossputin** [open-ecosystem-federation/federated-events-attributes-reasoning-alpha#25]
From 'OEF Ecosystem Governance'

Up to but not including 'Dimensions of Ecosystem Governance'

Please present your feedback as before in comments here on this ticket and @benghelps can hold the pen on merging the changes - thanks!

**Comment by sid250** [comment]
@benghelps @rossputin 

- Similar vein to what was suggested do we need to cover the entity model if it isn't something we are aiming for in the beta?
-In Figure 1, Could we discuss the difference between the master service agreement and the collaboration agreement? The two appear to be pretty close.
- We could arguably use a collaboration agreement for a bilateral relationship too. Does it always need to be a multilateral agreement?

**Comment by rossputin** [comment]
@benghelps @sid250 preparing for the session tomorrow and based on the content as listed in the email on 7 April here is some feedback on the final draft edits:

- 'terms of standardised models' models link does not seem to point to a specific section
- 'component parts' link does not seem to point to anything (I am guessing it should point to 'dimensions of ecosystem governance'
- 'dimensions of ecosystem governance' could maybe be re-labelled as components of ?
- a way to uniquely link to each of the components/dimensions

**Comment by rossputin** [comment]
@benghelps @sid250 closing this one as our call last week concluded it
