### ISSUE TITLE
untangle the use case collateral from the specification

### ISSUE THREAD

**Issue by rossputin** [open-ecosystem-federation/federated-events-attributes-reasoning-alpha#6]
Some thoughts for discussion @benghelps

A specification (and any Ecosystem Toolkit artefacts) should permit any interested parties to design and build an ecosystem for any given use case.

Subjectively I think we are conflating things by pushing our use case in to this material.

We could maybe look at the specification from a more axiomatic perspective, a little more focus on which mechanisms are required, and which optional, how things compose etc.  We can then point to an adjacent artefact which is a reference implementation around our use case.

**Comment by benghelps** [comment]
Agreed

**Comment by benghelps** [comment]
@rossputin - the Systems Context Diagram therefore needs to be normalised (e.g. remove reference to FSA, etc.)

**Comment by rossputin** [comment]
@benghelps - thanks for the heads up - done in the new level one (subjectively) simplest ecosystem - we can remove that more complex one and re-use when we move on to beta etc.

**Comment by rossputin** [comment]
I think this one can be closed @benghelps @bghelps - wdyt ?
